<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Employer extends Model
{
    use HasFactory;
    protected $primaryKey = 'EmployerID';
    protected $table = 'employer';
    public $timestamps = false;

    protected $fillable = [
        'EmployerID',
        'Departement',
        'Name',
        'NameEn',
        'Religion',
        'SexType',
        'BirthDay',
        'SocialStatus',
        'NationalityID',
        'SonNO',
        'Education',
        'job',
        'WorkHours',
        'Weekend',
        'Addresse',
        'NationalNo',
        'PostalCode',
        'Phone',
        'PhoneTwo',
        'Fax',
        'Email',
        'Amount',
        'City',
        'Governorate',
        'Town',
        'Area',
        'street',
        'house',
        'homeNo',
        'FamilyAddresse',
        'AccommodationNo',
        'AccommodationFinish',
        'passportNo',
        'passportEdit',
        'passportFinish',
        'Auto',
        'DrivingLicenseNo',
        'DrivingLicenseFinish',
        'isCollector',
        'Account',
        'CommissionAndFees',
        'CategorySalary',
        'CreditLimit',
        'LedgerId',
        'AdvancesId',
        'CustodyId',
        'EmpOneID',
        'EmpTwoID',
        'EmpThreeID',
        'IssuingTheSalaryBond',
        'CalculateTheratesOfPayAutomatically',
        'DistributionOfSalaryValue',
        'Salaryintervals',
        'CurrencyOfSalary',
        'FileOfPayroll',
        'Bank',
        'NumberOfBankAccount',
        'BasicSalary',
        'AccommodationAllowance',
        'TransitionAllowance',
        'WorkAllowace',
        'SocialAllowace',
        'PayDay',
        'PayHour',
        'TotalPayOfday',
        'TotalPayOfHour',
        'HealthInsuranceNo',
        'HealthInsuranceEdit',
        'HealthInsuranceFinish',
        'VacationTime',
        'AnnualLeavelDue',
        'CasualLeaveDue',
        'CalculatingAnnualLeaveMethodID',
        'CalculatingCasualLeaveMethodID',
        'LastAccountVacation',
        'AnnualLeaveBalance',
        'BalanceOfCasualLeave',
        'MaximumNumberOfLeave',
        'ContractType',
        'WorkType',
        'ServiceLeaveEntitlements',
        'BeginingOfDecade',
        'EndOfDecade',
        'StartingDate',
        'SocialSecurityNumber',
        'HealthInsuranceNumber',
        'EndOfHealthInsurance',
        'TheUnion',
        'TheUnion',
        'MilitaryService',
        'Dis',
        'UsrIns',
        'TimIns',
        'UsrUpd',
        'TimUpd'
    ];
}
