<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Vendor extends Model
{
    use HasFactory;
    protected $primaryKey = 'VendorID';
    protected $table = 'vendor';
    public $timestamps = false;
    protected $hidden = ['TimUpd', 'TimIns', 'Dis'];
    protected $fillable = [
        'VendorID',
        'VendorType',
        'Name',
        'NameEn',
        'SexType',
        'BirthDay',
        'AgeDay',
        'AgeMonth',
        'AgeYear',
        'SocialStatus',
        'Education',
        'job',
        'WorkHours',
        'Weekend',
        'Addresse',
        'NationalNo',
        'PostalCode',
        'Phone',
        'PhoneTwo',
        'Fax',
        'Email',
        'Amount',
        'City',
        'Governorate',
        'Town',
        'Area',
        'street',
        'house',
        'homeNo',
        'Responsible',
        'ResponsibleSeller',
        'RegisterationDate',
        'InsuranceNO',
        'InsuranceCompany',
        'InsuranceCompanyRatio',
        'RoomNo',
        'ExitDate',
        'DateLastSeen',
        'Stress',
        'Diabetes',
        'Smoking',
        'Account',
        'basicType',
        'CoastCenter',
        'OpeningBalance',
        'IsCreditable',
        'InsuranceLimit',
        'InsuranceLimitRemain',
        'InsurancePeriod',
        'InsurancePeriodFrom',
        'InsurancePeriodTo',
        'PriceId',
        'DiscountPercentage',
        'FixedDiscount',
        'BankAccount',
        'Religion',
        'PatientCode',
        'PatientType',
        'PatientClass',
        'FatherName',
        'GrandFatherName',
        'FatherNameEn',
        'GrandFatherNameEn',
        'NationalityID',
        'ReligionID',
        'PhoneRelatives',
        'mobile',
        'DebtLimit',
        'Discount',
        'InsuranceCardNO',
        'Nots',
        'Weight',
        'Lenght',
        'BloodType',
        'openningBalance',
        'currentBalance',
        'NextSeen',
        'Workplace',
        'firstCat',
        'secondCat',
        'thirdCat',
        'commercialNo',
        'Dis',
        'UsrIns',
        'TimIns',
        'UsrUpd',
        'TimUpd'
    ];
}
